spring.application.name=chakraEncryption2
# 1. MySQL Connection Settings
#spring.datasource.url=jdbc:mysql://localhost:3306/chakraEncryption?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.url=jdbc:mysql://localhost:3306/chakraEncryption?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chakraEncryption?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# 2. JPA / Hibernate Settings
# update kudutha, namma Java-la ezhudhara Entity-a vechu database-la table auto-ah create aagum.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Thymeleaf Settings (Caching off panna, code mathuna udane UI-la update aagum)
spring.thymeleaf.cache=false

# 4. Maximum file upload size (Image encryption-ku help aagum)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



# 5. Email Configuration for Security Alerts [cite: 2026-01-15]
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jk989437kumar@gmail.com
# Google Account "App Password" (16 digits) inga podanum
spring.mail.password=etfn mpnm zvcv udhy 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 6. Logging for Debugging
logging.level.com.example.chakraEncryption2=DEBUG